import { PhotoFrameConfig } from '../types/album';

export interface FramePreset {
  id: string;
  name: string;
  category: 'mat' | 'wood' | 'metallic' | 'vintage' | 'minimal' | 'fun' | 'custom';
  description: string;
  config: PhotoFrameConfig;
  previewCss: string;
}

export const FRAME_PRESETS: FramePreset[] = [
  // 1. None
  {
    id: 'none',
    name: 'Borderless (Standard)',
    category: 'minimal',
    description: 'Clean, full-bleed photo edge without additional frame.',
    config: {
      type: 'none',
      borderWidthMm: 0,
      borderColor: 'transparent',
    },
    previewCss: 'border: 1px dashed #cbd5e1; background: #f8fafc;',
  },

  // 2. Archival & Museum Mats (Passe-Partout)
  {
    id: 'classic-white-mat',
    name: 'Classic White Mat',
    category: 'mat',
    description: 'Crisp gallery white archival matting with subtle interior bevel.',
    config: {
      styleId: 'classic-white-mat',
      type: 'mat',
      borderWidthMm: 5,
      borderColor: '#ffffff',
      matColor: '#ffffff',
      matWidthMm: 4,
      innerBorderColor: 'rgba(0,0,0,0.12)',
      innerBorderWidthMm: 0.5,
      shadow: true,
      shadowBlurMm: 2,
    },
    previewCss: 'border: 6px solid #ffffff; box-shadow: inset 0 0 0 1px #cbd5e1, 0 3px 6px rgba(0,0,0,0.12); background: #ffffff;',
  },
  {
    id: 'warm-ivory-mat',
    name: 'Warm Ivory Museum Mat',
    category: 'mat',
    description: 'Warm cream cotton rag matting for fine art and wedding portraits.',
    config: {
      styleId: 'warm-ivory-mat',
      type: 'mat',
      borderWidthMm: 6,
      borderColor: '#fdfbf7',
      matColor: '#fbf8f0',
      matWidthMm: 4,
      innerBorderColor: 'rgba(120,90,50,0.18)',
      innerBorderWidthMm: 0.6,
      shadow: true,
      shadowBlurMm: 2.5,
    },
    previewCss: 'border: 6px solid #fdfbf7; box-shadow: inset 0 0 0 1px #e2dac9, 0 3px 6px rgba(0,0,0,0.1); background: #fbf8f0;',
  },
  {
    id: 'gallery-black-mat',
    name: 'Museum Jet Black Mat',
    category: 'mat',
    description: 'High-contrast matte black mat with crisp white core reveal.',
    config: {
      styleId: 'gallery-black-mat',
      type: 'mat',
      borderWidthMm: 6,
      borderColor: '#18181b',
      matColor: '#18181b',
      matWidthMm: 3,
      innerBorderColor: '#ffffff',
      innerBorderWidthMm: 0.6,
      shadow: true,
      shadowBlurMm: 3,
    },
    previewCss: 'border: 6px solid #18181b; box-shadow: inset 0 0 0 1px #ffffff, 0 4px 8px rgba(0,0,0,0.25); background: #18181b;',
  },
  {
    id: 'double-mat-gold',
    name: 'Double Mat with Gold Line',
    category: 'mat',
    description: 'Archival white outer mat paired with a delicate gold interior accent border.',
    config: {
      styleId: 'double-mat-gold',
      type: 'mat',
      borderWidthMm: 5,
      borderColor: '#ffffff',
      matColor: '#ffffff',
      matWidthMm: 3,
      innerBorderColor: '#d4af37',
      innerBorderWidthMm: 1.2,
      shadow: true,
      shadowBlurMm: 2.5,
    },
    previewCss: 'border: 5px solid #ffffff; box-shadow: inset 0 0 0 2px #d4af37, 0 3px 6px rgba(0,0,0,0.12); background: #ffffff;',
  },
  {
    id: 'double-mat-charcoal',
    name: 'Double Mat with Charcoal',
    category: 'mat',
    description: 'Alabaster white outer mat paired with an architectural charcoal reveal line.',
    config: {
      styleId: 'double-mat-charcoal',
      type: 'mat',
      borderWidthMm: 5,
      borderColor: '#ffffff',
      matColor: '#ffffff',
      matWidthMm: 3,
      innerBorderColor: '#334155',
      innerBorderWidthMm: 1.0,
      shadow: true,
      shadowBlurMm: 2.5,
    },
    previewCss: 'border: 5px solid #ffffff; box-shadow: inset 0 0 0 1.5px #334155, 0 3px 6px rgba(0,0,0,0.12); background: #ffffff;',
  },

  // 3. Natural Wood Frames
  {
    id: 'nordic-oak',
    name: 'Nordic Light Oak',
    category: 'wood',
    description: 'Clean, warm natural oak timber with light organic grain.',
    config: {
      styleId: 'nordic-oak',
      type: 'wood',
      borderWidthMm: 4,
      borderColor: '#d8b98a',
      innerBorderColor: '#bfa06f',
      innerBorderWidthMm: 0.5,
      texture: 'wood',
      shadow: true,
      shadowBlurMm: 3,
    },
    previewCss: 'border: 5px solid #d8b98a; box-shadow: inset 0 0 0 1px #bfa06f, 0 4px 8px rgba(0,0,0,0.15); background: #fdfbf7;',
  },
  {
    id: 'dark-walnut',
    name: 'Dark Walnut Frame',
    category: 'wood',
    description: 'Rich, deep espresso walnut timber with subtle wood warmth.',
    config: {
      styleId: 'dark-walnut',
      type: 'wood',
      borderWidthMm: 4.5,
      borderColor: '#3e2723',
      innerBorderColor: '#2b1b17',
      innerBorderWidthMm: 0.6,
      texture: 'wood',
      shadow: true,
      shadowBlurMm: 3.5,
    },
    previewCss: 'border: 5px solid #3e2723; box-shadow: inset 0 0 0 1px #231613, 0 4px 8px rgba(0,0,0,0.25); background: #f8fafc;',
  },
  {
    id: 'rustic-driftwood',
    name: 'Weathered Driftwood',
    category: 'wood',
    description: 'Coastal grey-washed weathered wood with organic rustic character.',
    config: {
      styleId: 'rustic-driftwood',
      type: 'wood',
      borderWidthMm: 4.5,
      borderColor: '#a8a29e',
      innerBorderColor: '#78716c',
      innerBorderWidthMm: 0.5,
      texture: 'wood',
      shadow: true,
      shadowBlurMm: 2.5,
    },
    previewCss: 'border: 5px solid #a8a29e; box-shadow: inset 0 0 0 1px #78716c, 0 3px 6px rgba(0,0,0,0.15); background: #fafaf9;',
  },
  {
    id: 'bleached-white-ash',
    name: 'Bleached White Ash',
    category: 'wood',
    description: 'Scandinavian whitewashed ash wood frame with a breezy modern aesthetic.',
    config: {
      styleId: 'bleached-white-ash',
      type: 'wood',
      borderWidthMm: 4,
      borderColor: '#f5f5f4',
      innerBorderColor: '#e7e5e4',
      innerBorderWidthMm: 0.5,
      texture: 'wood',
      shadow: true,
      shadowBlurMm: 2,
    },
    previewCss: 'border: 5px solid #f5f5f4; box-shadow: inset 0 0 0 1px #d6d3d1, 0 3px 6px rgba(0,0,0,0.1); background: #ffffff;',
  },

  // 4. Luxe Metallics
  {
    id: 'brushed-gold',
    name: 'Brushed Royal Gold',
    category: 'metallic',
    description: 'Champagne gold metallic border with radiant inner bevel highlights.',
    config: {
      styleId: 'brushed-gold',
      type: 'metallic',
      borderWidthMm: 3.5,
      borderColor: '#d4af37',
      innerBorderColor: '#aa820a',
      innerBorderWidthMm: 0.8,
      shadow: true,
      shadowBlurMm: 2.5,
    },
    previewCss: 'border: 4px solid #d4af37; box-shadow: inset 0 0 0 1px #fff3b0, 0 3px 8px rgba(180,140,20,0.25); background: #ffffff;',
  },
  {
    id: 'matte-silver',
    name: 'Architectural Silver',
    category: 'metallic',
    description: 'Sleek brushed platinum silver edge with crisp modern sheen.',
    config: {
      styleId: 'matte-silver',
      type: 'metallic',
      borderWidthMm: 3,
      borderColor: '#cbd5e1',
      innerBorderColor: '#94a3b8',
      innerBorderWidthMm: 0.5,
      shadow: true,
      shadowBlurMm: 2,
    },
    previewCss: 'border: 4px solid #cbd5e1; box-shadow: inset 0 0 0 1px #f1f5f9, 0 3px 6px rgba(0,0,0,0.12); background: #ffffff;',
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold Luxe',
    category: 'metallic',
    description: 'Gentle blush metallic luster perfect for wedding & celebration albums.',
    config: {
      styleId: 'rose-gold',
      type: 'metallic',
      borderWidthMm: 3.5,
      borderColor: '#e0a899',
      innerBorderColor: '#ba7a68',
      innerBorderWidthMm: 0.6,
      shadow: true,
      shadowBlurMm: 2.5,
    },
    previewCss: 'border: 4px solid #e0a899; box-shadow: inset 0 0 0 1px #fae1da, 0 3px 6px rgba(200,120,100,0.2); background: #ffffff;',
  },
  {
    id: 'antique-bronze',
    name: 'Antique Patina Bronze',
    category: 'metallic',
    description: 'Deep oxidized bronze with vintage warmth and rich metallic weight.',
    config: {
      styleId: 'antique-bronze',
      type: 'metallic',
      borderWidthMm: 4,
      borderColor: '#6b4f3b',
      innerBorderColor: '#422f22',
      innerBorderWidthMm: 0.7,
      shadow: true,
      shadowBlurMm: 3,
    },
    previewCss: 'border: 4px solid #6b4f3b; box-shadow: inset 0 0 0 1px #8c6a51, 0 4px 8px rgba(0,0,0,0.25); background: #ffffff;',
  },

  // 5. Vintage & Creative
  {
    id: 'polaroid-classic',
    name: 'Classic Polaroid Print',
    category: 'vintage',
    description: 'Iconic instant film format with extended bottom margin for captions.',
    config: {
      styleId: 'polaroid-classic',
      type: 'polaroid',
      borderWidthMm: 3.5,
      borderColor: '#faf9f6',
      matColor: '#faf9f6',
      bottomExtraMm: 8,
      innerBorderColor: 'rgba(0,0,0,0.1)',
      innerBorderWidthMm: 0.4,
      shadow: true,
      shadowBlurMm: 3.5,
      caption: '',
    },
    previewCss: 'border: 4px solid #faf9f6; border-bottom-width: 14px; box-shadow: 0 4px 10px rgba(0,0,0,0.18); background: #faf9f6;',
  },
  {
    id: 'polaroid-warm-cream',
    name: 'Vintage Polaroid Cream',
    category: 'vintage',
    description: 'Aged cream instant snapshot with nostalgic retro warmth.',
    config: {
      styleId: 'polaroid-warm-cream',
      type: 'polaroid',
      borderWidthMm: 4,
      borderColor: '#f7f2e7',
      matColor: '#f7f2e7',
      bottomExtraMm: 9,
      innerBorderColor: 'rgba(100,70,30,0.15)',
      innerBorderWidthMm: 0.4,
      shadow: true,
      shadowBlurMm: 4,
      caption: '',
    },
    previewCss: 'border: 4px solid #f7f2e7; border-bottom-width: 16px; box-shadow: 0 4px 10px rgba(0,0,0,0.15); background: #f7f2e7;',
  },
  {
    id: 'vintage-35mm-slide',
    name: '35mm Film Slide Mount',
    category: 'vintage',
    description: 'Authentic 35mm transparency slide mount with corner guides.',
    config: {
      styleId: 'vintage-35mm-slide',
      type: 'vintage',
      borderWidthMm: 4.5,
      borderColor: '#f4f0ea',
      innerBorderColor: '#1e293b',
      innerBorderWidthMm: 0.6,
      cornerRadiusMm: 1.5,
      shadow: true,
      shadowBlurMm: 3,
    },
    previewCss: 'border: 5px solid #f4f0ea; box-shadow: inset 0 0 0 1px #1e293b, 0 3px 6px rgba(0,0,0,0.15); border-radius: 3px; background: #ffffff;',
  },
  {
    id: 'film-negative',
    name: 'Film Negative Border',
    category: 'vintage',
    description: 'Dark cinema negative edge with frame exposure markers.',
    config: {
      styleId: 'film-negative',
      type: 'vintage',
      borderWidthMm: 3.5,
      borderColor: '#09090b',
      innerBorderColor: 'rgba(255,255,255,0.15)',
      innerBorderWidthMm: 0.5,
      shadow: true,
      shadowBlurMm: 3,
    },
    previewCss: 'border: 4px solid #09090b; box-shadow: inset 0 0 0 1px rgba(255,255,255,0.2), 0 4px 8px rgba(0,0,0,0.3); background: #000000;',
  },

  // 6. Modern Minimal & Card Float
  {
    id: 'fine-black-line',
    name: 'Architectural Hairline',
    category: 'minimal',
    description: 'Ultra-thin 0.8mm crisp black boundary for clean modern layouts.',
    config: {
      styleId: 'fine-black-line',
      type: 'minimal',
      borderWidthMm: 0.8,
      borderColor: '#18181b',
      shadow: false,
    },
    previewCss: 'border: 1.5px solid #18181b; background: transparent;',
  },
  {
    id: 'fine-white-line',
    name: 'Crisp White Separator',
    category: 'minimal',
    description: 'Clean white separation line, ideal over dark or textured backgrounds.',
    config: {
      styleId: 'fine-white-line',
      type: 'minimal',
      borderWidthMm: 1.2,
      borderColor: '#ffffff',
      shadow: true,
      shadowBlurMm: 1.5,
    },
    previewCss: 'border: 2px solid #ffffff; box-shadow: 0 1px 3px rgba(0,0,0,0.2); background: transparent;',
  },
  {
    id: 'rounded-card',
    name: 'Modern Rounded Card',
    category: 'minimal',
    description: 'Subtly rounded corners (3mm radius) with an ambient soft drop shadow.',
    config: {
      styleId: 'rounded-card',
      type: 'minimal',
      borderWidthMm: 0,
      borderColor: 'transparent',
      cornerRadiusMm: 3.5,
      shadow: true,
      shadowBlurMm: 3,
    },
    previewCss: 'border: 1px solid #e2e8f0; border-radius: 6px; box-shadow: 0 4px 8px rgba(0,0,0,0.12); background: #ffffff;',
  },
  {
    id: 'soft-squircle',
    name: 'Contemporary Squircle',
    category: 'minimal',
    description: 'Generously rounded corners (6mm radius) creating soft contemporary aesthetics.',
    config: {
      styleId: 'soft-squircle',
      type: 'minimal',
      borderWidthMm: 0,
      borderColor: 'transparent',
      cornerRadiusMm: 6,
      shadow: true,
      shadowBlurMm: 4,
    },
    previewCss: 'border: 1px solid #e2e8f0; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.14); background: #ffffff;',
  },
  {
    id: 'float-mount',
    name: 'Gallery Float Mount',
    category: 'minimal',
    description: 'Frameless floating print look with deep ambient drop shadow.',
    config: {
      styleId: 'float-mount',
      type: 'minimal',
      borderWidthMm: 0,
      borderColor: 'transparent',
      shadow: true,
      shadowBlurMm: 5,
    },
    previewCss: 'box-shadow: 0 8px 18px rgba(0,0,0,0.22); border: 1px solid rgba(0,0,0,0.06); background: #ffffff;',
  },

  // 6. Fun & Decorative: Floral & Smiley
  {
    id: 'floral-blossom',
    name: 'Blossom Floral Border',
    category: 'fun',
    description: 'Pastel rose border with hand-illustrated corner flower blossoms and leafy vines.',
    config: {
      styleId: 'floral-blossom',
      type: 'floral',
      borderWidthMm: 5,
      borderColor: '#fdf2f4',
      matColor: '#fcf0f2',
      innerBorderColor: '#e0a9b5',
      innerBorderWidthMm: 0.5,
      shadow: true,
      shadowBlurMm: 2.5,
      cornerRadiusMm: 2,
    },
    previewCss: 'border: 5px solid #fdf2f4; outline: 1px solid #f4cfd7; box-shadow: 0 3px 6px rgba(220,100,120,0.15); background: #fff5f7;',
  },
  {
    id: 'floral-vintage',
    name: 'Golden Botanical Garden',
    category: 'fun',
    description: 'Fine art sage and gold floral corner motifs with vintage appeal.',
    config: {
      styleId: 'floral-vintage',
      type: 'floral',
      borderWidthMm: 6,
      borderColor: '#f4f6f0',
      matColor: '#eff3ea',
      innerBorderColor: '#b5c4a6',
      innerBorderWidthMm: 0.6,
      shadow: true,
      shadowBlurMm: 3,
      cornerRadiusMm: 1.5,
    },
    previewCss: 'border: 6px solid #f4f6f0; outline: 1px solid #c2ceb6; box-shadow: 0 3px 6px rgba(80,110,70,0.12); background: #fbfdf9;',
  },
  {
    id: 'happy-smiley',
    name: 'Joyful Sunshine Smiley',
    category: 'fun',
    description: 'Bright sunshine yellow frame accented with cheerful smiling emoji corner badges.',
    config: {
      styleId: 'happy-smiley',
      type: 'smiley',
      borderWidthMm: 5.5,
      borderColor: '#fef08a',
      matColor: '#fef9c3',
      innerBorderColor: '#f59e0b',
      innerBorderWidthMm: 0.6,
      cornerRadiusMm: 4,
      shadow: true,
      shadowBlurMm: 2.5,
    },
    previewCss: 'border: 5px solid #fef08a; outline: 1px solid #fde047; box-shadow: 0 3px 6px rgba(245,158,11,0.2); background: #fefce8;',
  },
  {
    id: 'smiley-pop',
    name: 'Pop Party Smileys',
    category: 'fun',
    description: 'Vibrant punchy smiley frame perfect for birthdays, vacations, and celebrations.',
    config: {
      styleId: 'smiley-pop',
      type: 'smiley',
      borderWidthMm: 6.5,
      borderColor: '#fed7aa',
      matColor: '#ffedd5',
      innerBorderColor: '#fb923c',
      innerBorderWidthMm: 0.7,
      cornerRadiusMm: 5,
      shadow: true,
      shadowBlurMm: 3,
    },
    previewCss: 'border: 6px solid #fed7aa; outline: 1px solid #fdba74; box-shadow: 0 4px 8px rgba(249,115,22,0.2); background: #fff7ed;',
  },
  {
    id: 'custom-frame-upload',
    name: 'Custom Uploaded Frame',
    category: 'custom',
    description: 'Upload your own PNG frame, border artwork, or sticker graphic.',
    config: {
      styleId: 'custom-frame-upload',
      type: 'custom_image',
      borderWidthMm: 5,
      borderColor: '#ffffff',
      shadow: true,
      shadowBlurMm: 2,
    },
    previewCss: 'border: 2px dashed #94a3b8; background: #f8fafc;',
  },
];

export function getFramePresetById(id?: string): FramePreset {
  if (!id) return FRAME_PRESETS[0];
  return FRAME_PRESETS.find((p) => p.id === id) || FRAME_PRESETS[0];
}
